# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rspec-rails-extra-routing}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Hugo Roque (a.k.a HugoLnx)"]
  s.date = %q{2011-04-04}
  s.description = %q{Extension to rspec-rails that allows some shortcuts in routing tests.
With it, this:
  describe "users routes" do
    describe "GET /" do
      it{{:get => '/'}.should route_to "users#index"}
    end

    describe "POST /" do
      it{{:post => '/'}.should be_routable}
    end
  end

can be written like this:

  describe "users routes" do
    get('/').should route_to "users#index"
    post('/').should be_routable
  end
}
  s.email = %q{hugo.roque@caelum.com.br}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "lib/rspec-rails-extra-routing.rb",
    "lib/rspec/rails/extra.rb",
    "lib/rspec/rails/extra/routing.rb",
    "lib/rspec/rails/extra/routing/hyper_shortcut.rb",
    "lib/rspec/rails/extra/routing/hyper_shortcut/additional_methods.rb",
    "lib/rspec/rails/extra/routing/hyper_shortcut/behavior.rb",
    "lib/rspec/rails/extra/routing/hyper_shortcut/matcher_placeholder.rb",
    "lib/rspec/rails/extra/routing/hyper_shortcut/request_pair.rb",
    "lib/rspec/rails/extra/routing/hyper_shortcut/routing_example_group.rb",
    "lib/rspec/rails/extra/routing/hyper_shortcut/shortcut_elements.rb",
    "lib/rspec/rails/extra/routing/hyper_shortcut/subject_placeholder.rb"
  ]
  s.homepage = %q{http://github.com/HugoLnx/rspec-rails-extra-routing}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Extension to rspec-rails that allows some shortcuts in routing tests}
  s.test_files = [
    "spec/hyper_shortcut/behavior_spec.rb",
    "spec/hyper_shortcut/matcher_placeholder_spec.rb",
    "spec/hyper_shortcut/request_pair_spec.rb",
    "spec/hyper_shortcut/shortcut_elements_spec.rb",
    "spec/hyper_shortcut/subject_placeholder_spec.rb",
    "spec/spec_helper.rb",
    "test/helper.rb",
    "test/test_rspec-rails-routing-plus.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_runtime_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_runtime_dependency(%q<rcov>, ["= 0.9.9"])
      s.add_runtime_dependency(%q<rspec-rails>, [">= 2.5.0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, ["= 0.9.9"])
      s.add_dependency(%q<rspec-rails>, [">= 2.5.0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, ["= 0.9.9"])
    s.add_dependency(%q<rspec-rails>, [">= 2.5.0"])
  end
end

